version: "2"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - proto
    - web
    - infra

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign

formatters:
  enable:
    - gofumpt

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  max-issues-per-run: 0
