services:
  postgres-ads:
    image: postgres:16
    container_name: adhub-postgres-ads
    restart: always
    environment:
      POSTGRES_USER: adhub
      POSTGRES_PASSWORD: adhub
      POSTGRES_DB: adhub_ads
    ports:
      - "5433:5432"
    volumes:
      - pgdata_ads:/var/lib/postgresql/data
    networks:
      - adhub-net

  prometheus:
    image: prom/prometheus:latest
    container_name: adhub-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - adhub-net

  grafana:
    image: grafana/grafana:latest
    container_name: adhub-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - adhub-net

  postgres-users:
    image: postgres:16
    container_name: adhub-postgres-users
    restart: always
    environment:
      POSTGRES_USER: adhub
      POSTGRES_PASSWORD: adhub
      POSTGRES_DB: adhub_users
    ports:
      - "5434:5432"
    volumes:
      - pgdata_ads:/var/lib/postgresql/data
    networks:
      - adhub-net

  ads:
    build:
      context: .
      dockerfile: cmd/ads/Dockerfile
    container_name: adhub-ads
    ports:
      - "8081:8081"
    env_file: cmd/ads/.env
    environment:
      DATABASE_URL: postgres://adhub:adhub@postgres-ads:5432/adhub_ads?sslmode=disable
    depends_on:
      - postgres-ads
    networks:
      - adhub-net

  graphql-gateway:
    build:
      context: .
      dockerfile: cmd/graphql-gateway/Dockerfile
    container_name: adhub-graphql-gateway
    env_file: cmd/ads/.env
    ports:
      - "8083:8083"
    environment:
      DATABASE_URL: postgres://adhub:adhub@postgres-ads:5432/adhub_ads?sslmode=disable
    depends_on:
      - postgres-ads
    networks:
      - adhub-net

  auth:
    build:
      context: .
      dockerfile: cmd/auth/Dockerfile
    container_name: adhub-auth
    ports:
      - "8082:8082"
    depends_on:
      - postgres-users
    networks:
      - adhub-net

networks:
  adhub-net:

volumes:
  pgdata_ads:
  pgdata_users:
