FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/auth ./cmd/auth

RUN chmod +x /app/auth

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/auth .

EXPOSE 8082
ENTRYPOINT ["/app/auth"]
